modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   displayURL="${curseforge_url}"
   logoFile="${logo_file}"
   #credits="Thanks for this example mod goes to Java"
   authors="${mod_authors}"
   description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="super_ore_block"
   mandatory=true
   versionRange="${super_ore_block_version_range_forge}"
   ordering="NONE"
   side="BOTH"
